# SPDX-FileCopyrightText: © 2024 Tiny Tapeout
# SPDX-License-Identifier: Apache-2.0

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, Timer, RisingEdge, Event, with_timeout
from cocotb.result import SimTimeoutError


# ============================================================
# UART PARAMETERS
# ============================================================

CLK_FREQ = 200_000_000
BAUD_RATE = 9600

# 200 MHz / 9600 ≈ 20833 clocks per UART bit
# Match the integer divider used by the RTL
BAUD_COUNT = 20833

# 200 MHz clock = 5 ns
CLK_PERIOD_NS = 5

# Actual UART bit period generated by the RTL
BIT_TIME_NS = BAUD_COUNT * CLK_PERIOD_NS
HALF_BIT_TIME_NS = BIT_TIME_NS // 2


# ============================================================
# PIN MAPPING
# ============================================================

# ui_in
TX_DATA_MASK = 0xFF

# uio_in
RX_PIN = 0
TX_START_PIN = 1

# uio_out
TX_PIN = 2
TX_BUSY_PIN = 3
TX_DONE_PIN = 4
RX_DONE_PIN = 5
FRAMING_ERROR_PIN = 6


# ============================================================
# RESET
# ============================================================

async def reset_dut(dut):

    dut._log.info("Resetting DUT")

    dut.ena.value = 1
    dut.ui_in.value = 0

    # RX idle = 1
    dut.uio_in.value = 1 << RX_PIN

    dut.rst_n.value = 0

    await ClockCycles(dut.clk, 10)

    dut.rst_n.value = 1

    # Keep RX idle HIGH
    dut.uio_in.value = 1 << RX_PIN

    await ClockCycles(dut.clk, 10)

    dut._log.info("Reset complete")


# ============================================================
# HELPER: SET TX START
# ============================================================

async def start_tx(dut, data):

    dut._log.info(f"Starting TX with data = 0x{data:02X}")

    # Put data on ui_in
    dut.ui_in.value = data

    # RX remains idle HIGH
    # TX_START = 1
    dut.uio_in.value = (
        (1 << RX_PIN) |
        (1 << TX_START_PIN)
    )

    await ClockCycles(dut.clk, 1)

    # TX_START back to 0
    dut.uio_in.value = (1 << RX_PIN)

    dut._log.info("TX start pulse sent")


# ============================================================
# HELPER: WAIT FOR TX DONE
# ============================================================

async def wait_for_tx_done(dut, done_event):

    while True:

        await RisingEdge(dut.clk)

        tx_done = (
            (int(dut.uio_out.value) >> TX_DONE_PIN) & 1
        )

        if tx_done:
            dut._log.info("TX_DONE pulse detected")
            done_event.set()
            return


# ============================================================
# HELPER: WAIT FOR RX DONE
# ============================================================

async def wait_for_rx_done(dut, done_event):

    while True:

        await RisingEdge(dut.clk)

        rx_done = (
            (int(dut.uio_out.value) >> RX_DONE_PIN) & 1
        )

        if rx_done:
            dut._log.info("RX_DONE pulse detected")
            done_event.set()
            return


# ============================================================
# TEST 1: TX
# ============================================================

@cocotb.test()
async def test_uart_tx(dut):

    dut._log.info("================================")
    dut._log.info("UART TX TEST")
    dut._log.info("================================")

    # Start 200 MHz clock
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())

    await reset_dut(dut)

    test_data = 0xA5

    # --------------------------------------------------------
    # Start monitoring TX_DONE BEFORE starting transmission
    # --------------------------------------------------------

    tx_done_event = Event()

    cocotb.start_soon(
        wait_for_tx_done(dut, tx_done_event)
    )

    # Start TX
    await start_tx(dut, test_data)

    # --------------------------------------------------------
    # Wait for TX to become busy
    # --------------------------------------------------------

    for _ in range(20):

        if (
            (int(dut.uio_out.value) >> TX_BUSY_PIN) & 1
        ):
            break

        await ClockCycles(dut.clk, 1)

    tx_busy = (
        (int(dut.uio_out.value) >> TX_BUSY_PIN) & 1
    )

    assert tx_busy == 1, "TX did not become busy"

    dut._log.info("TX became busy")

    # --------------------------------------------------------
    # UART frame
    #
    # START = 0
    # DATA  = D0 D1 ... D7
    # STOP  = 1
    # --------------------------------------------------------

    expected_bits = []

    # Start bit
    expected_bits.append(0)

    # 8 data bits, LSB first
    for i in range(8):
        expected_bits.append(
            (test_data >> i) & 1
        )

    # Stop bit
    expected_bits.append(1)

    dut._log.info(
        f"Expected UART frame: {expected_bits}"
    )

    # --------------------------------------------------------
    # Sample approximately in the middle of every bit
    # --------------------------------------------------------

    for bit_number, expected in enumerate(expected_bits):

        await Timer(
            HALF_BIT_TIME_NS,
            unit="ns"
        )

        tx_value = (
            (int(dut.uio_out.value) >> TX_PIN) & 1
        )

        dut._log.info(
            f"TX bit {bit_number}: "
            f"expected={expected}, "
            f"actual={tx_value}"
        )

        assert tx_value == expected, (
            f"TX bit {bit_number} incorrect: "
            f"expected {expected}, "
            f"got {tx_value}"
        )

        await Timer(
            HALF_BIT_TIME_NS,
            unit="ns"
        )

    # --------------------------------------------------------
    # Wait for TX_DONE
    # --------------------------------------------------------

    try:

        await with_timeout(
            tx_done_event.wait(),
            20,
            "us"
        )

    except SimTimeoutError:

        assert False, "TX done was not asserted"

    dut._log.info("TX done detected")

    dut._log.info("TX test PASSED")


# ============================================================
# HELPER: SEND UART BYTE INTO RX
# ============================================================

async def send_uart_byte(dut, data):

    dut._log.info(
        f"Sending UART RX byte = 0x{data:02X}"
    )

    # --------------------------------------------------------
    # START BIT
    # --------------------------------------------------------

    dut.uio_in.value = 0

    await Timer(
        BIT_TIME_NS,
        unit="ns"
    )

    # --------------------------------------------------------
    # DATA BITS - LSB FIRST
    # --------------------------------------------------------

    for i in range(8):

        bit = (data >> i) & 1

        # RX is uio_in[0]
        dut.uio_in.value = bit

        dut._log.info(
            f"RX sending D{i} = {bit}"
        )

        await Timer(
            BIT_TIME_NS,
            unit="ns"
        )

    # --------------------------------------------------------
    # STOP BIT
    # --------------------------------------------------------

    dut.uio_in.value = 1

    await Timer(
        BIT_TIME_NS,
        unit="ns"
    )

    # Return to UART idle
    dut.uio_in.value = 1


# ============================================================
# TEST 2: RX
# ============================================================

@cocotb.test()
async def test_uart_rx(dut):

    dut._log.info("================================")
    dut._log.info("UART RX TEST")
    dut._log.info("================================")

    # Start 200 MHz clock
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())

    await reset_dut(dut)

    test_data = 0xA5

    # --------------------------------------------------------
    # Start monitoring RX_DONE BEFORE sending the frame
    # --------------------------------------------------------

    rx_done_event = Event()

    cocotb.start_soon(
        wait_for_rx_done(dut, rx_done_event)
    )

    # --------------------------------------------------------
    # Send UART frame
    # --------------------------------------------------------

    await send_uart_byte(dut, test_data)

    # --------------------------------------------------------
    # Wait for RX_DONE
    # --------------------------------------------------------

    try:

        await with_timeout(
            rx_done_event.wait(),
            20,
            "us"
        )

    except SimTimeoutError:

        assert False, "RX done was not asserted"

    dut._log.info("RX done detected")

    # --------------------------------------------------------
    # Read received data
    # --------------------------------------------------------

    received_data = (
        int(dut.uo_out.value) & TX_DATA_MASK
    )

    dut._log.info(
        f"RX expected = 0x{test_data:02X}"
    )

    dut._log.info(
        f"RX received = 0x{received_data:02X}"
    )

    assert received_data == test_data, (
        f"RX data incorrect: "
        f"expected 0x{test_data:02X}, "
        f"got 0x{received_data:02X}"
    )

    # --------------------------------------------------------
    # Check framing error
    # --------------------------------------------------------

    framing_error = (
        (int(dut.uio_out.value) >> FRAMING_ERROR_PIN) & 1
    )

    assert framing_error == 0, (
        "Unexpected framing error"
    )

    dut._log.info("RX test PASSED")


# ============================================================
# TEST 3: RX MULTIPLE BYTES
# ============================================================

@cocotb.test()
async def test_uart_rx_multiple_bytes(dut):

    dut._log.info("================================")
    dut._log.info("UART MULTIPLE RX TEST")
    dut._log.info("================================")

    # Start 200 MHz clock
    clock = Clock(dut.clk, CLK_PERIOD_NS, unit="ns")
    cocotb.start_soon(clock.start())

    await reset_dut(dut)

    test_values = [
        0x00,
        0x55,
        0xAA,
        0xA5,
        0xFF,
        0x42
    ]

    # --------------------------------------------------------
    # Test each byte
    # --------------------------------------------------------

    for test_data in test_values:

        dut._log.info(
            f"Testing RX value 0x{test_data:02X}"
        )

        # ----------------------------------------------------
        # Create a NEW RX_DONE monitor for this byte
        # ----------------------------------------------------

        rx_done_event = Event()

        cocotb.start_soon(
            wait_for_rx_done(dut, rx_done_event)
        )

        # ----------------------------------------------------
        # Send UART byte
        # ----------------------------------------------------

        await send_uart_byte(dut, test_data)

        # ----------------------------------------------------
        # Wait for RX_DONE
        # ----------------------------------------------------

        try:

            await with_timeout(
                rx_done_event.wait(),
                20,
                "us"
            )

        except SimTimeoutError:

            assert False, (
                f"RX done not detected for "
                f"0x{test_data:02X}"
            )

        dut._log.info(
            f"RX done detected for 0x{test_data:02X}"
        )

        # ----------------------------------------------------
        # Check received data
        # ----------------------------------------------------

        received_data = (
            int(dut.uo_out.value) & TX_DATA_MASK
        )

        dut._log.info(
            f"RX expected = 0x{test_data:02X}"
        )

        dut._log.info(
            f"RX received = 0x{received_data:02X}"
        )

        assert received_data == test_data, (
            f"RX mismatch: "
            f"expected 0x{test_data:02X}, "
            f"got 0x{received_data:02X}"
        )

        # ----------------------------------------------------
        # Check framing error
        # ----------------------------------------------------

        framing_error = (
            (int(dut.uio_out.value) >> FRAMING_ERROR_PIN) & 1
        )

        assert framing_error == 0, (
            f"Unexpected framing error for "
            f"0x{test_data:02X}"
        )

        # ----------------------------------------------------
        # Allow RX to return to IDLE
        # ----------------------------------------------------

        await ClockCycles(dut.clk, 10)

    dut._log.info(
        "Multiple RX test PASSED"
    )
